### ISSUE TITLE
Nonstandard string literal syntax

### ISSUE THREAD

**Issue by zsunberg** [sisl/Spot.jl#1]
It might be neat (and it would be very Julian) to have a special string literal (https://docs.julialang.org/en/v1/manual/metaprogramming/#Non-Standard-String-Literals-1) for ltl statements. Then you could write, e.g.
```julia
ltl = ltl"FG A"
```
and it would automatically convert it into some kind of LTL object.

There may be some issues with that, but just thought I'd share the thought.

**Comment by MaximeBouton** [comment]
It should be possible now. 

I already had defined a wrapper for `SpotFormula`. The syntax `ltl"FG a"`  is equivalent to calling the constructor `SpotFormula("FG a")`

**Comment by mykelk** [comment]
So beautiful.
