### ISSUE TITLE
Using CxxWrap.jl instead of Cxx.jl

### ISSUE THREAD

**Issue by MaximeBouton** [sisl/Spot.jl#13]
CxxWrap.jl is more stable and it would allow Spot.jl to work on julia 1.6. Here is the roadmap: 

- [x] implement the c++ wrapper https://github.com/MaximeBouton/jlspot 
- [x] test Spot on ubuntu using the wrapper compiled from CxxWrap.jl 
- [x] submit the wrapper to Yggdrasil as libspot_julia to get a jll package 
- [x] make Spot depend on the jll
- [x] upgrade CI 
- [ ] upgrade docs (doc website?)
- [x] tag a new version

**Comment by MaximeBouton** [comment]
looking good :) I think I will delay the CI upgrade and docs after tagging a new version and make sure POMDPModelChecking.jl works before.

**Comment by rejuvyesh** [comment]
@MaximeBouton close issue?
