### ISSUE TITLE
Spot.jl doesn't work on current version of Julia

### ISSUE THREAD

**Issue by bakirtzisg** [sisl/Spot.jl#20]
We would like to incorporate Spot.jl but it doesn't seem to compile from the registry properly throwing some C++ errors. Is there a plan to make Spot.jl current or should we consider it unmaintained?

> julia> include("test.jl")
> [ Info: Precompiling Spot [f11abc24-ce50-11e8-2475-af6658d13f2b]
> C++ exception while wrapping module Spot: invalid subtyping in definition of Formula with supertype Any
> ERROR: LoadError:
> signal (11): Segmentation fault
> in expression starting at none:0
> sweep_pool_page at /buildworker/worker/package_linux64/build/src/gc.c:1392 [inlined]
> sweep_pool_pagetable0 at /buildworker/worker/package_linux64/build/src/gc.c:1412 [inlined]
> sweep_pool_pagetable1 at /buildworker/worker/package_linux64/build/src/gc.c:1432 [inlined]
> sweep_pool_pagetable at /buildworker/worker/package_linux64/build/src/gc.c:1462 [inlined]
> gc_sweep_pool at /buildworker/worker/package_linux64/build/src/gc.c:1537
> _jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:3153
> jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:3248
> maybe_collect at /buildworker/worker/package_linux64/build/src/gc.c:882 [inlined]
> jl_gc_pool_alloc at /buildworker/worker/package_linux64/build/src/gc.c:1209
> jl_gc_alloc_ at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
> jl_gc_alloc at /buildworker/worker/package_linux64/build/src/gc.c:3290
> _new_array_ at /buildworker/worker/package_linux64/build/src/array.c:127 [inlined]
> _new_array at /buildworker/worker/package_linux64/build/src/array.c:193 [inlined]
> jl_alloc_array_1d at /buildworker/worker/package_linux64/build/src/array.c:441
> Array at ./boot.jl:457 [inlined]
> Array at ./boot.jl:476 [inlined]
> IncrementalCompact at ./compiler/ssair/ir.jl:614
> compact! at ./compiler/ssair/ir.jl:1441
> compact! at ./compiler/ssair/ir.jl:1441 [inlined]
> run_passes at ./compiler/optimize.jl:317
> optimize at ./compiler/optimize.jl:296 [inlined]
> _typeinf at ./compiler/typeinfer.jl:255
> typeinf at ./compiler/typeinfer.jl:209
> abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:557
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:113
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:557
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:113
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:557
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:113
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1900
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_edge at ./compiler/typeinfer.jl:823 [inlined]
> abstract_call_method at ./compiler/abstractinterpretation.jl:504
> abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:105
> abstract_call_known at ./compiler/abstractinterpretation.jl:1342
> abstract_call at ./compiler/abstractinterpretation.jl:1397
> abstract_call at ./compiler/abstractinterpretation.jl:1382
> abstract_eval_statement at ./compiler/abstractinterpretation.jl:1534
> typeinf_local at ./compiler/abstractinterpretation.jl:1918
> typeinf_nocycle at ./compiler/abstractinterpretation.jl:2014
> _typeinf at ./compiler/typeinfer.jl:226
> typeinf at ./compiler/typeinfer.jl:209
> typeinf_ext at ./compiler/typeinfer.jl:909
> typeinf_ext_toplevel at ./compiler/typeinfer.jl:942
> typeinf_ext_toplevel at ./compiler/typeinfer.jl:938
> jfptr_typeinf_ext_toplevel_10577.clone_1 at /home/undergrad/julia-1.7.2/lib/julia/sys.so (unknown line)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
> jl_type_infer at /buildworker/worker/package_linux64/build/src/gf.c:295
> jl_generate_fptr at /buildworker/worker/package_linux64/build/src/jitlayers.cpp:338
> jl_compile_method_internal at /buildworker/worker/package_linux64/build/src/gf.c:1980
> jl_compile_method_internal at /buildworker/worker/package_linux64/build/src/gf.c:2246 [inlined]
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2239 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> #showerror#814 at ./errorshow.jl:96
> showerror##kw at ./errorshow.jl:95
> unknown function (ip: 0x7f540d1aa151)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> show_exception_stack at ./errorshow.jl:866
> jfptr_show_exception_stack_40505.clone_1 at /home/undergrad/julia-1.7.2/lib/julia/sys.so (unknown line)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> display_error at ./client.jl:104
> unknown function (ip: 0x7f540d1a8706)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> display_error at ./client.jl:107
> unknown function (ip: 0x7f540d1a7c12)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
> jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:757
> #invokelatest#2 at ./essentials.jl:716 [inlined]
> invokelatest at ./essentials.jl:714 [inlined]
> _start at ./client.jl:497
> jfptr__start_38732.clone_1 at /home/undergrad/julia-1.7.2/lib/julia/sys.so (unknown line)
> _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
> jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
> jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
> true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:559
> jl_repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:701
> main at /buildworker/worker/package_linux64/build/cli/loader_exe.c:42
> __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
> _start at /home/undergrad/julia-1.7.2/bin/julia (unknown line)
> Allocations: 7288539 (Pool: 7286579; Big: 1960); GC: 4
> ERROR: LoadError: Failed to precompile Spot [f11abc24-ce50-11e8-2475-af6658d13f2b] to /home/undergrad/.julia/compiled/v1.7/Spot/jl_Tv5DWO.
> Stacktrace:
>  [1] error(s::String)
>    @ Base ./error.jl:33
>  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
>    @ Base ./loading.jl:1466
>  [3] compilecache(pkg::Base.PkgId, path::String)
>    @ Base ./loading.jl:1410
>  [4] _require(pkg::Base.PkgId)
>    @ Base ./loading.jl:1120
>  [5] require(uuidkey::Base.PkgId)
>    @ Base ./loading.jl:1013
>  [6] require(into::Module, mod::Symbol)
>    @ Base ./loading.jl:997
>  [7] include(fname::String)
>    @ Base.MainInclude ./client.jl:451
>  [8] top-level scope
>    @ REPL[3]:1
> in expression starting at /home/undergrad/TylerIngebrand/Contracts/test.jl:1

File is:

> using Spot
> 
> ltl = "FG A"
> translator = LTLTranslator(deterministic=true)
> 
> a = translate(translator, ltl)

**Comment by mykelk** [comment]
@MaximeBouton any thoughts?

**Comment by MaximeBouton** [comment]
I am a bit rusty on this but could it be that the Spot_julia_jll library needs to be recompiled? 

The build file in Yggdrasil is here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/Spot_julia/build_tarballs.jl 

@bakirtzisg could you try making a merge request to Yggdrasil updating the build_tarballs.jl? 
I will not be able to look into it before August. 

The source code for the wrapped c++ function is here: https://github.com/MaximeBouton/spot_julia/ if it is useful, but hopefully it is just a matter of recompiling with the updated julia libraries.

**Comment by bakirtzisg** [comment]
@MaximeBouton I have made a pull request to change the Julia version in the build script to 1.7. Its possible this just fixes it, but I have never done anything with Yggdrasil so I could be completely off mark.

**Comment by MaximeBouton** [comment]
Hey @bakirtzisg, I cannot find your pull request can you link it here?

**Comment by MaximeBouton** [comment]
I created a new one here https://github.com/JuliaPackaging/Yggdrasil/pull/5282 
and a PR to spot (still work in progress) #21

**Comment by bakirtzisg** [comment]
Thanks @MaximeBouton, I was wondering if you had figured out what the issue fundamentally is? I am still not quite sure.

**Comment by MaximeBouton** [comment]
I am working on this again, let's see if it works after the PR to Yggdrasil gets merged

**Comment by MaximeBouton** [comment]
@bakirtzisg good news! Spot is working on the latest julia 1.8. (It should also work on 1.7). 
The master branch has been updated, and a new release is being registered, v0.2.2. I will close this issue as soon as the registration process has completed.
