### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by Can-ZHOU** [sisl/Spot.jl#22]
Hi! Many thanks for developing this package. However, I encountered some problems when I tried to install the Spot package on Windows. It seems to indicate that I still need Cxx.jl instead of CxxWrap.jl. I was wondering if there is any solution to this?

Many thanks in advance!

**Comment by MaximeBouton** [comment]
I think this is an issue with the compatibility bounds we set for CxxWrap.jl. However, even if we try to update it there still seems to be some issues (segfault). 
Stay tuned #23.

**Comment by MaximeBouton** [comment]
This should be resolved now :)
